# Generated by Django 3.0.6 on 2020-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigetmovie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favmovie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
