# Generated by Django 3.0.6 on 2020-06-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigetmovie', '0002_auto_20200614_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favmovie',
            name='followers',
        ),
        migrations.AlterField(
            model_name='favmovie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.ManyToManyField(to='apigetmovie.FavMovie')),
            ],
        ),
    ]
