# Generated by Django 3.0.6 on 2020-06-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigetmovie', '0003_auto_20200614_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('fav_id', models.ManyToManyField(to='apigetmovie.FavMovie')),
            ],
        ),
        migrations.DeleteModel(
            name='UserFav',
        ),
    ]
