# Generated by Django 3.0.6 on 2020-06-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigetmovie', '0004_auto_20200614_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavid',
            name='fav_id',
            field=models.ManyToManyField(help_text='id for movie', to='apigetmovie.FavMovie'),
        ),
    ]
