# Generated by Django 3.0.6 on 2020-06-14 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apigetmovie', '0006_remove_userfavid_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='favmovie',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserFavID',
        ),
    ]
