# Generated by Django 3.0.6 on 2020-06-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigetmovie', '0008_auto_20200614_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav',
            name='type',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
